Disable CDN communication
minvws/nl-covid19-notification-app-ios pull request #86
Opened 2022-09-15 08:13 UTC by 7hommay

Adds a stubbed NetworkManager returning fixed responses for manifest and app config

Fixes https://github.com/minvws/nl-covid19-notification-app-coordination-private/issues/32

2022-09-15 09:03 UTC, skos001 submitted a review, later dismissed

2022-09-15 10:14 UTC, skos001 approved these changes, later dismissed

2022-09-20 09:13 UTC, hvisser requested changes

2022-09-20 09:13 UTC, hvisser commented on Sources/ENCore/Common/NetworkManager/NetworkManagerBuilder.swift
> +//        Disable network traffic
Would be better to just remove this vs commenting this out IMHO

2022-09-21 08:15 UTC, nicktencate commented
@Rool can you take a look?

2022-09-21 08:52 UTC, Rool commented
I agree with @hvisser. Remove the commented out networkmanager in the builder

2022-09-21 08:53 UTC, Rool commented
And three of the tests are failing:

ENCoreTests.EndOfLifeViewControllerTests
  test_snapshot_endOfLifeViewController, failed - Snapshot does not match reference.
  /Users/runner/work/nl-covid19-notification-app-ios/nl-covid19-notification-app-ios/Sources/ENCoreTests/App/Features/EndOfLifeViewController/EndOfLifeViewControllerTests.swift:35
  ```
    func test_snapshot_endOfLifeViewController() {
        snapshots(matching: viewController)
    }
  ```

  test_snapshot_endOfLifeViewController, failed - Snapshot does not match reference.
  /Users/runner/work/nl-covid19-notification-app-ios/nl-covid19-notification-app-ios/Sources/ENCoreTests/App/Features/EndOfLifeViewController/EndOfLifeViewControllerTests.swift:35
  ```
    func test_snapshot_endOfLifeViewController() {
        snapshots(matching: viewController)
    }
  ```

  test_snapshot_endOfLifeViewController, failed - Snapshot does not match reference.
  /Users/runner/work/nl-covid19-notification-app-ios/nl-covid19-notification-app-ios/Sources/ENCoreTests/App/Features/EndOfLifeViewController/EndOfLifeViewControllerTests.swift:35
  ```
    func test_snapshot_endOfLifeViewController() {
        snapshots(matching: viewController)
    }
  ```

2022-09-21 08:54 UTC, hvisser commented
@Rool can you fix this in absence of @7hommay ?

2022-09-21 08:59 UTC, Rool commented
Will try to fix this. Give me an hour or so.

2022-09-21 11:28 UTC, Rool commented
I ran into openSSL errors while running the tests. So I temporarily disabled the failing snapshot tests.

2022-09-26 10:18 UTC, Rool commented
The same three snapshots keep failing on CI.

2022-09-26 10:22 UTC, hvisser commented
@Rool I've noticed ;) Working on it, CI has different results vs running these locally 🥲

2022-09-26 11:37 UTC, Rool approved these changes, later dismissed

2022-09-26 11:50 UTC, hvisser approved these changes

2022-09-26 13:18 UTC, merged